[package]
name = "rr-bench-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bigdecimal = "0.4.5"
openssl = "0.10.66"
pg_bigdecimal = "0.1.5"
postgres = "0.19.8"
postgres-openssl = "0.5.0"
r2d2_postgres = "0.18.1"
rr-bench-core = { path = "../rr-bench-core" }
